version: "3.9"

services:
  rag-app:
    build: .
    container_name: rag_app
    ports:
      - "8000:8000"
      - "8501:8501"
    environment:
      - FASTAPI_URL=http://host.docker.internal:8000
    extra_hosts:
      - "host.docker.internal:host-gateway"
